image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V # Print out python version for debugging

test:
  stage: test
  script:
    - pip install pipenv
    - pipenv install --dev
    - pipenv run coverage run && pipenv run coverage html
    # - pip install tox flake8  # you can also use tox
    # - tox -e py36,flake8
  artifacts:
    paths:
      - htmlcov/

# run:
#   script:
#     - python setup.py bdist_wheel
#     # an alternative approach is to install and run:
#     - pip install dist/*
#     # run the command here
#   artifacts:
#     paths:
#       - dist/*.whl

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
