image: python:latest

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}

test:
  stage: test
  before_script:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
  script:
    - poetry install
    - poetry run coverage run
    - poetry run coverage html
    # - pip install tox flake8  # you can also use tox
    # - tox -e py36,flake8
  artifacts:
    paths:
      - htmlcov/

build:
  stage: deploy
  before_script:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
  script:
    - poetry publish --build -u $PYPI_USERNAME -p $PYPI_PASSWORD
  only:
    - master

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

code_quality:
  after_script:
    - cat gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths: [gl-code-quality-report.json]
