image: python:latest

stages:
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}

test:
  stage: test
  script:
    - pip install tox
    - tox

merge_test:
  stage: test
  script:
    - pip install tox
    - tox
  only:
    - merge_requests

build:
  stage: deploy
  allow_failure: true
  before_script:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
  script:
    - poetry publish --build -u $PYPI_USERNAME -p $PYPI_PASSWORD
  only:
    - master
