version = "v1"

[[platforms]]
name = "macos"

  [platforms.platform_info]
  version = 10.0

[[modules]]
name = "full"
module_type = "group"
requires = [
  "dotfiles",
  "zsh"
]

[[modules]]
name = "zsh"
module_type = "app"
version = "5.3"
requires = [
  "brew",
  "git-subrepo",
  "fasd",
  "pipenv",
  "private_var"
]
commands = [
  "sudo sh -c \"echo /usr/local/bin/zsh >> /etc/shells\" && chsh -s $(which zsh)",
  "ln -sf ~/dotfiles/zsh/zshrc_manager.sh ~/.zshrc",
  "ln -sf ~/dotfiles/zsh/zimrc.sh ~/.zimrc",
  "ln -sf ~/dotfiles/zsh/zlogin.sh ~/.zlogin",
  "ln -sf ~/dotfiles/zsh/zshenv.sh ~/.zshenv"
]

[[modules]]
alias = "dotfiles"
module_type = "folder"
owner = "justine"
permission = "744"
name = "dotfiles"
parent_dir = "~/"
requires = [
  "git"
]
init = [
  "git clone git@gitlab.com:justinekizhak/dotfiles.git"
]
command = "None"

[[modules]]
alias = "private_var"
module_type = "file"
name = "private_env_var.sh"
parent_dir = "~/dotfiles/zsh/"
