version:
  type: string
platforms:
  type: list
  schema:
    type: dict
    schema:
      alias:
        type: string
      name:
        type: string
        required: True
      display:
        type: string
      default:
        type: string
      check:
        type: dict
        schema:
          version:
            type: string
          command:
            type: string
      presets:
        type: list
        schema:
          type: dict
          schema:
            alias:
              type: string
            name:
              type: string
              required: True
            display:
              type: string
            requires:
              type: list
              schema:
                type: string
            optionals:
              type: list
              schema:
                type: string
      apps:
        type: list
        schema:
          type: dict
          schema:
            alias:
              type: string
            name:
              type: string
              required: True
            display:
              type: string
            check:
              type: dict
              schema:
                version:
                  type: string
                command:
                  type: string
            requires:
              type: list
              schema:
                type: string
            optionals:
              type: list
              schema:
                type: string
            steps:
              type: list
              schema:
                type: string
      folders:
        type: list
        schema:
          type: dict
          schema:
            alias:
              type: string
            name:
              type: string
              required: True
            display:
              type: string
            owner:
              type: string
            permission:
              type: string
            parent_dir:
              type: string
            is_empty:
              type: boolean
            requires:
              type: list
              schema:
                type: string
            optionals:
              type: list
              schema:
                type: string
            steps:
              type: list
              schema:
                type: string
      files:
        type: list
        schema:
          type: dict
          schema:
            alias:
              type: string
            owner:
              type: string
            permission:
              type: string
            name:
              type: string
              required: True
            parent_dir:
              type: string
            requires:
              type: list
              schema:
                type: string
            optionals:
              type: list
              schema:
                type: string
            steps:
              type: list
              schema:
                type: string
