version:
  type: string
platforms:
  type: list
  schema:
    type: dict
    schema:
      alias:
        type: string
      name:
        type: string
        required: True
      display:
        type: string
      default:
        type: string
      package_manager:
        type: string
      version:
        type: dict
        schema:
          identifier:
            type: string
            required: True
          command:
            type: string
            required: True
      presets:
        type: list
        schema:
          type: dict
          schema:
            alias:
              type: string
            name:
              type: string
              required: True
            display:
              type: string
            requires:
              type: list
              schema:
                type: string
            optionals:
              type: list
              schema:
                type: string
      modules:
        type: list
        schema:
          type: dict
          schema:
            alias:
              type: string
            name:
              type: string
              required: True
            display:
              type: string
              nullable: True
            version:
              type: dict
              schema:
                identifier:
                  type: string
                  required: True
                command:
                  type: string
                  required: True
            requires:
              type: list
              schema:
                type: string
            optionals:
              type: list
              schema:
                type: string
            command:
              type: string
              nullable: True
            init:
              type: list
              schema:
                type: string
            config:
              type: list
              schema:
                type: string
            executable:
              type: string
      folders:
        type: list
        schema:
          type: dict
          schema:
            alias:
              type: string
            name:
              type: string
              required: True
            display:
              type: string
              nullable: True
            owner:
              type: string
            permission:
              type: string
            parent_dir:
              type: string
            requires:
              type: list
              schema:
                type: string
            optionals:
              type: list
              schema:
                type: string
            init:
              type: list
              schema:
                type: string
            command:
              type: string
              nullable: True
            config:
              type: list
              schema:
                type: string
      files:
        type: list
        schema:
          type: dict
          schema:
            alias:
              type: string
            owner:
              type: string
            permission:
              type: string
            name:
              type: string
              required: True
            parent_dir:
              type: string
            requires:
              type: list
              schema:
                type: string
            optionals:
              type: list
              schema:
                type: string
            display:
              type: string
              nullable: True
            init:
              type: list
              schema:
                type: string
            command:
              type: string
              nullable: True
            config:
              type: list
              schema:
                type: string
